name: Deploy Node.js App with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Copy files to EC2
      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r . ec2-user@${{ secrets.HOST }}:/home/ec2-user/app

      # Deploy the app on EC2
      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.HOST }} << 'EOF'
          cd /home/ec2-user/app
          npm install
          pm2 start server.js --name node-app
          pm2 save
          sudo env PATH=$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u ec2-user --hp /home/ec2-user
          EOF

      # Verify PM2 Process
      - name: Check PM2 Status
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.HOST }} << 'EOF'
          pm2 list
          EOF
